CREATE DATABASE customer_behaviour;
USE customer_behaviour;
SHOW TABLES;

SELECT COUNT(*) 
FROM customer_shopping_behavior;

-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer_shopping_behavior
GROUP BY gender;

-- Q2. Which customers used a discount but still spend more than the average purchase amount?
SELECT customer_id, discount_applied
FROM customer_shopping_behavior
WHERE discount_applied = 'Yes' AND ( SELECT AVG(purchase_amount) FROM customer_shopping_behavior) <= purchase_amount;

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS average_rating
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY average_rating DESC
LIMIT 5;

-- Q4. Compare the average purchase amounts between standard and express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS average_purchase_amt
FROM customer_shopping_behavior
WHERE shipping_type = 'Express' or shipping_type = 'Standard'
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status, Count(customer_id) AS total_customers, ROUND(AVG(purchase_amount),2) AS average_spend, SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
	item_purchased, 
	ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)*100,2) AS discount_rate
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, Loyal based on their total number of prev purchases, and show the count of each segment.

SELECT 
    (CASE 
		WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' ELSE 'Loyal' 
	END) AS loyalty,
    COUNT(*) AS customer_count
FROM customer_shopping_behavior
GROUP BY loyalty
ORDER BY customer_count DESC;
    
-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) AS item_rank
from customer_shopping_behavior
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY revenue DESC;

